variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image:
    name: klakegg/hugo:ext-alpine
    entrypoint : ['']
  before_script:
    - git submodule update --init --recursive
  script:
    - hugo --gc --minify && gzip -k -6 $(find public -type f)
  artifacts:
    paths:
      - public
  only:
    - main
